INSERT INTO reviews(
    username, movie, comments, food, rating)
    VALUES
    ('daniel', 'Almost Famous', 'Despite taking place in the middle of the raucous 1970s, this film is a timeless coming-of-age story that will appeal to viewers regardless of whether or not they were around during the era. In Almost Famous the palette director Cameron Crowe paints from is an autobiographical one. The colors he uses are at once yellow and gray...', 'hotdog', '5'),
    ('dannyboy', 'Finding Nemo', 'Finding Nemo 3D is another example of post-conversion done right and, paired with the especially humorous Partysaurus Rex short, is well worth another trip to your local box office. To find Nemo is to discover underwater treasure. The animation has the depth of the ocean itself. The adventure is both fun and fulfilling. And the lessons just keep on swimming.','popcorn', '4'),
    ('hansol', 'Inglourious Basterds', 'Quentin Tarantinos latest effort is a World War II fable pitting a band of ferocious Jews against the Third Reichs wickedness. Bizarre, bold, and bloody, theres no denying that "Inglourious Basterds" has all the vim, vigor, and excitement of Quentin Tarantinos other films. This might just be my masterpiece, runs the last line of Inglourious Basterds. While that may not be true, its an often dazzling movie that sees QT back on exhilarating form' , 'taco', '4'),
    ('matt', 'Minority Report', 'In a perfect world murderers would be caught before they could kill and the innocent would never live in fear. The movie is visually stunning with brilliantly staged action sequences and vividly realized characters. As with Blade Runner also based on a story by Philip K.', 'burger', '5'),
    ('vince', 'Blood Diamond', 'These days we think as little about where mall diamonds come from as where grocery store food is grown. Blood Diamond aims to change that fact with a fictional story inspired by facts. Great performances, provocative ideas and gripping action scenes fall prey to Hollywood logic and pat storytelling in the final hour.', 'taco', '4'),
    ('clint', 'True Grit', 'Terrific tough, exciting, funny, gorgeous and bewitchingly acted, this is darn close to perfection. In this Western filled with gorgeous landscapes and action-packed shootouts, the Coen brothers display a vision of a Wild West that is indeed wild -- but also honorable. It takes some serious grit to turn a John Wayne classic into a darkly ambiguous comedy. The results are both mesmerizing and maddening.', 'taco', '5'),
    ('jane', 'Casino Royale', ' Bond is back (to the beginning), leaner, meaner and stripped of any hint of camp. Daniel Craigs 007 is a killers killer in a decidedly darker, post 9/11 world.', 'taco', '3'),
    ('connor', 'WALL-E', 'Another out-of-this-world Pixar picture. And this time that label applies to the setting, too, as a lonely little robot named WALL-E finds and follows the lovely EVE across the universe.', 'taco', '5'),
    ('niko', 'Gran Torino', 'Simply terrific, enormously watchable and an absolute must for all Eastwood fans. Gotta say it: this film will make your day. Far from being about a car, Gran Torino is another chapter in Clint Eastwoods ongoing quest to explore choices of dignity and disgrace, life and death.', 'taco', '3')
;